
name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install metadata validator dependencies
        run: |
          wget https://github.com/unicode-org/icu/releases/download/release-71-1/icu4c-71_1-Ubuntu20.04-x64.tgz
          tar -xf icu4c-71_1-Ubuntu20.04-x64.tgz

          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ github.workspace }}/icu/usr/local/lib" >> "$GITHUB_ENV"

      - name: Install metadata validator
        run: wget https://github.com/loot/metadata-validator/releases/download/0.21.0/metadata-validator-0.21.0-0-gd56177b_0.21.0-Linux.tar.xz -O - | tar -xJ --strip-components=1

      - name: Install parser
        run: npm install -g js-yaml

      - name: Run js-yaml to check YAML parsing
        run: js-yaml $GITHUB_WORKSPACE/prelude.yaml > /dev/null

      - name: Run metadata validator against each game's masterlist
        run: |
          # Run validation against the latest version of each game's masterlist
          # to catch integration issues.
          games=(
            morrowind
            oblivion
            skyrim
            skyrimse
            skyrimvr
            fallout3
            falloutnv
            fallout4
            fallout4vr
            enderal
            starfield
          )

          for game in "${games[@]}"
          do
            wget --no-verbose -O masterlist.yaml https://raw.githubusercontent.com/loot/$game/v0.21/masterlist.yaml
            ./metadata_validator masterlist.yaml $GITHUB_WORKSPACE/prelude.yaml
          done
