
name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-24.04

    env:
      MASTERLIST_BRANCH: v0.29
      VALIDATOR_VERSION: 0.29.0

    steps:
      - uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install metadata validator v${{ env.VALIDATOR_VERSION }}
        run: wget https://github.com/loot/metadata-validator/releases/download/${{ env.VALIDATOR_VERSION }}/metadata-validator-${{ env.VALIDATOR_VERSION }}-Linux.tar.xz -O - | tar -xJ --strip-components=1

      - name: Install parser
        run: npm install -g js-yaml

      - name: Run js-yaml to check YAML parsing
        run: js-yaml prelude.yaml > /dev/null

      - name: Run metadata validator against each game's masterlist
        run: |
          # Run validation against the latest version of each game's masterlist
          # to catch integration issues.
          games=(
            morrowind
            oblivion
            skyrim
            skyrimse
            fallout3
            falloutnv
            fallout4
            enderal
            starfield
          )

          for game in "${games[@]}"
          do
            wget --no-verbose -O masterlist.yaml https://raw.githubusercontent.com/loot/$game/${MASTERLIST_BRANCH}/masterlist.yaml

            ./metadata_validator masterlist.yaml prelude.yaml
          done
