
name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install metadata validator dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-upgrade \
            libicu74 \
            libtbb12

      - name: Install metadata validator v0.26.1
        run: |
          wget https://github.com/loot/metadata-validator/releases/download/0.26.1/metadata-validator-0.26.1-0-g23e0aa1_0.26.1-Linux.tar.xz -O - | tar -xJ --strip-components=1
          ln -s libloot.so.0.26.1 libloot.so.0

      - name: Install metadata validator v0.28.2
        run: wget https://github.com/loot/metadata-validator/releases/download/0.28.2/metadata-validator-0.28.2-Linux.tar.xz -O - | tar -xJ

      - name: Install parser
        run: npm install -g js-yaml

      - name: Run js-yaml to check YAML parsing
        run: js-yaml prelude.yaml > /dev/null

      - name: Run metadata validator against each game's masterlist
        run: |
          # Run validation against the latest version of each game's masterlist
          # to catch integration issues.
          games=(
            morrowind
            oblivion
            skyrim
            skyrimse
            fallout3
            falloutnv
            fallout4
            enderal
            starfield
          )

          for game in "${games[@]}"
          do
            wget --no-verbose -O masterlist.yaml https://raw.githubusercontent.com/loot/$game/v0.26/masterlist.yaml

            ./metadata_validator masterlist.yaml prelude.yaml

            ./metadata-validator-0.28.2-Linux/metadata_validator masterlist.yaml prelude.yaml
          done
