
name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libstdc++6 libhttp-parser-dev libssh2-1-dev

      - name: Set up Node
        uses: actions/setup-node@v1

      - name: Install metadata validator
        run: wget https://github.com/loot/metadata-validator/releases/download/0.17.0/metadata-validator-0.17.0-0-gf29ef61_0.17.0-Linux.tar.xz -O - | tar -xJ --strip-components=1

      - name: Install parser
        run: npm install -g js-yaml

      - name: Run js-yaml to check YAML parsing
        run: js-yaml $GITHUB_WORKSPACE/prelude.yaml > /dev/null

      - name: Run metadata validator against each game's masterlist
        run: |
          # Run validation against the latest version of each game's masterlist
          # to catch integration issues.
          games=(
            morrowind
            oblivion
            skyrim
            skyrimse
            fallout3
            falloutnv
            fallout4
            enderal
          )

          for game in "${games[@]}"
          do
            wget --no-verbose -O masterlist.yaml https://raw.githubusercontent.com/loot/$game/v0.17/masterlist.yaml
            ./metadata_validator masterlist.yaml $GITHUB_WORKSPACE/prelude.yaml
          done
