name: Export translations from prelude

on:
  pull_request:
    paths: [prelude.yaml]
  push:
    paths: [prelude.yaml]

jobs:
  export:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv .venv
          ./.venv/bin/activate
          pip install -r requirements.txt

      - name: Run the export translations script
        run: python scripts/export-translations.py

      - name: Create patch containing changes
        run: git diff > sync-translations.patch

      - name: Record pull request head data
        run: |
          echo 'export PR_HEAD_URL="${{ github.event.pull_request.head.repo.clone_url }}"' > git_vars.sh
          echo 'export PR_HEAD_REF="${{ github.event.pull_request.head.ref }}"' >> git_vars.sh
          echo 'export COMMIT_MESSAGE="Export translations from prelude"' >> git_vars.sh
        if: ${{ github.event_name == 'pull_request' }}

      - name: Record pull request head data
        run: |
          echo 'export PR_HEAD_URL="${{ github.event.push.repository.clone_url }}"' > git_vars.sh
          echo 'export PR_HEAD_REF="${{ github.event.push.ref }}"' >> git_vars.sh
          echo 'export COMMIT_MESSAGE="Export translations from prelude"' >> git_vars.sh
        if: ${{ github.event_name == 'push' }}

      - name: Upload data
        uses: actions/upload-artifact@v4
        with:
          name: sync-translations-data
          path: |
            sync-translations.patch
            git_vars.sh
