on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-24.04

    env:
      PRELUDE_BRANCH: v0.29
      VALIDATOR_VERSION: 0.29.0

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install metadata validator v${{ env.VALIDATOR_VERSION }}
        run: wget https://github.com/loot/metadata-validator/releases/download/${{ env.VALIDATOR_VERSION }}/metadata-validator-${{ env.VALIDATOR_VERSION }}-Linux.tar.xz -O - | tar -xJ --strip-components=1

      - name: Install parser
        run: npm install -g js-yaml

      - name: Download prelude file
        run: wget https://raw.githubusercontent.com/loot/prelude/${PRELUDE_BRANCH}/prelude.yaml

      - name: Run metadata validator
        run: |
          ./metadata_validator masterlist.yaml
          ./metadata_validator masterlist.yaml prelude.yaml

          js-yaml masterlist.yaml > /dev/null
